# Generated by Django 4.1.1 on 2022-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_department_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hr',
            field=models.BooleanField(default=False),
        ),
    ]
