# Generated by Django 4.1.1 on 2022-10-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_per_day1',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_rate1',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_leave',
            field=models.IntegerField(null=True),
        ),
    ]
