# Generated by Django 3.1.1 on 2022-11-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_requestleave_isdeclined'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestleave',
            name='AdminApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestleave',
            name='AdminDeclined',
            field=models.BooleanField(default=False),
        ),
    ]
